### ISSUE TITLE
ArgumentOutOfRangeException in Scraper

### ISSUE THREAD

**Issue by Zebradil** [Kudoser/SteamTogether#34]
```
fail: Microsoft.Extensions.Hosting.Internal.Host[9]
      BackgroundService failed
      System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'period')
         at System.Threading.PeriodicTimer..ctor(TimeSpan period)
         at SteamTogether.Scraper.Worker.ExecuteAsync(CancellationToken stoppingToken) in /src/SteamTogether.Scraper/Worker.cs:line 37
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
crit: Microsoft.Extensions.Hosting.Internal.Host[10]
      The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
      System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'period')
         at System.Threading.PeriodicTimer..ctor(TimeSpan period)
         at SteamTogether.Scraper.Worker.ExecuteAsync(CancellationToken stoppingToken) in /src/SteamTogether.Scraper/Worker.cs:line 37
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
```

**Comment by ablizorukov** [comment]
With which options did you run the app? How to repeat?

**Comment by Zebradil** [comment]
It was spotted on production, I don't know how to reproduce. My assumption here is that the period became zero, which is not allowed by the timer.

I did some changes there, check the PR.
